### ISSUE TITLE
í types 0 instead

### ISSUE THREAD

**Issue by TamasBarta** [adamkovesdi/hupckeylayout#1]
Hi!

The layout is a great help for me.
However, í types 0 on a 2018 Macbook Pro 13" with touch bar. Do you think you can resolve it?
Thanks!

**Comment by adamkovesdi** [comment]
@TamasBarta I know a long time has passed but let me try anyways. I don't have an ISO layout Mac and neither the software anymore but I believe if you change line 96 in Hungarian-PC.keylayout file, you'll get there:

https://github.com/adamkovesdi/hupckeylayout/blob/8a623733d1e1c27aab664892eaaaae8bfc639bf1/Hungarian-PC.keylayout#L96
Just change "0" to "í"

Reference:
![Apple keyboard layouts](https://i.stack.imgur.com/LD8pT.png)

**Comment by TamasBarta** [comment]
Thanks! I use another PC layout now, and with this current model I use, it works well, but I'm sure this is useful for those that end up here from Google or something. I'll close the issue now.
